# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base node image
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Use a smaller image for the final product
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist ./dist
COPY package.json ./

# Install only production dependencies
RUN npm install --omit=dev --ignore-scripts

# Set environment variables if needed
# ENV COINCAP_API_KEY=<YOUR_API_KEY>

# Command to run the application
ENTRYPOINT ["node", "dist/index.js"]
